### ISSUE TITLE
Could not install Gradle distribution from 'http://artifactory.cde.huawei.com/artifactory/gradle-distributions-cache/gradle-6.3-bin.zip'.

### ISSUE THREAD

**Issue by steven-gao** [HMS-Core/hms-AREngine-demo#10]
hi,
我导入demo到Android studio，报如下错误
Could not install Gradle distribution from 'http://artifactory.cde.huawei.com/artifactory/gradle-distributions-cache/gradle-6.3-bin.zip'.
请问怎么处理？

**Comment by remmel** [comment]
In `gradle-wrapper.properties` use:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip`

**Comment by remmel** [comment]
Fixed in https://github.com/HMS-Core/hms-AREngine-demo/commit/2f845336079d085c87a4afad34d6d3c7c6bf98c3

**Comment by steven-gao** [comment]
@remmel thank you,yes, u are right
