### ISSUE TITLE
想问下使用华为AR Engine必需要注册华为开发者联盟吗？不注册对上架华为市场有影响吗

### ISSUE THREAD

**Issue by fancychendong** [HMS-Core/hms-AREngine-demo#11]
如题

**Comment by Mike-mei** [comment]
在开发应用前需要在[华为开发者联盟](https://developer.huawei.com/consumer/cn/?ha_source=hms1)网站上注册成为开发者并完成实名认证，具体方法请参见[帐号注册认证](https://developer.huawei.com/consumer/cn/doc/start/account-registration-and-authentication1-0000001053768010?ha_source=hms1)，不注册是提交不了上架申请的。
