### ISSUE TITLE
com.huawei.hiar.exceptions.ARFatalException

### ISSUE THREAD

**Issue by fancychendong** [HMS-Core/hms-AREngine-demo#12]
![image](https://user-images.githubusercontent.com/3930976/178184017-17e01539-5d90-4525-afe5-9972be03444f.png)
Help~
ArFrame update()  happen
#1 ​kotlinx.coroutines.CoroutineId#main
com.huawei.hiar.exceptions.ARFatalException

前后台状态：前台
设备机型：ABR-AL60
系统版本：Android 11,level 30
ROM：HuaWei/EMOTION
CPU架构：arm64-v8a

**Comment by Xuejiao-Shi** [comment]
您可以看一下这个文档  看看是不是哪里配置有问题：
![image](https://user-images.githubusercontent.com/99166105/178221915-06e62dd8-a733-4bab-bf93-62b4136253ab.png)
https://developer.huawei.com/consumer/cn/doc/development/graphics-References/fatal_exception-0000001050162194?ha_source=hms1
