### ISSUE TITLE
isAREngineApkReady 不可用了 demo好使 自测也好使 今日突然不好使了

### ISSUE THREAD

**Issue by shougonyiren** [HMS-Core/hms-AREngine-demo#16]

**Comment by shougonyiren** [comment]
s Install AR Engine Apk:false

**Comment by shougonyiren** [comment]
就一台测试机这样

**Comment by xuxiapu** [comment]
@shougonyiren 尊敬的开发者您好，
请问目前isAREngineApkReady 可以用了吗？如果不可用的话，麻烦提供一下错误信息的日志，以便开发人员定位问题所在。

**Comment by shougonyiren** [comment]
可以用了&nbsp; &nbsp;感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月4日(周三) 上午9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HMS-Core/hms-AREngine-demo] isAREngineApkReady 不可用了 demo好使 自测也好使 今日突然不好使了 (Issue #16)




 
@shougonyiren 尊敬的开发者您好，
 请问目前isAREngineApkReady 可以用了吗？如果不可用的话，麻烦提供一下错误信息的日志，以便开发人员定位问题所在。
