### ISSUE TITLE
Torch mode does not work

### ISSUE THREAD

**Issue by lvonasek** [HMS-Core/hms-AREngine-demo#2]
I added into WorldActivity.java following line:
config.setEnableItem(ARConfigBase.ENABLE_FLASH_MODE_TORCH);

This should enable flashlight but it does nothing on my Honor View 20.

**Comment by Mike-mei** [comment]
Sorry, enabling flashlight is not supported currently. We will support this function in the future version. Thank you very much for your concerns.

**Comment by lvonasek** [comment]
Should not this stay opened as long as it is not resolved yet?
