### ISSUE TITLE
请问下hms AREngine目前版本是否支持把一个view放到ar世界坐标系中？

### ISSUE THREAD

**Issue by jjq3** [HMS-Core/hms-AREngine-demo#5]
请问下hms AREngine目前版本（2.13.0.2版本）是否支持根据一个三维坐标的x,y,z值去把一个view放到ar世界坐标系中？盼答复 谢谢！

**Comment by Mike-mei** [comment]
支持的，AR Engine可以提供锚定View的有向点（位置和姿态）的相机参数，渲染需要应用自己实现，建议您参考sample code中虚拟物体的绘制。
