### ISSUE TITLE
请问可以计算身高肩宽之类的数据吗?

### ISSUE THREAD

**Issue by JiangMingJieJie** [HMS-Core/hms-AREngine-demo#6]

**Comment by ferPrieto** [comment]
Hey @JiangMingJieJie , you can get data info from the different body parts that belongs the ARBoty.ARBodySkeletonType, such as _BodySkeleton_Length_

I would suggest you to check **ARBody.class** to understand this information.
Debugging functions as _static ARBody.ARBodySkeletonType forNumber(int nativeCode)_ will provide you the values you need.
