### ISSUE TITLE
Cannot change the preview size ARConfigBase.setPreviewSize(w,h)

### ISSUE THREAD

**Issue by remmel** [HMS-Core/hms-AREngine-demo#7]
According to [2.13 release note](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/version-change-history-0000001050132857-V5), the [ARConfigBase.setPreviewSize(w,h)](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/config_base-0000001050119488-V5#EN-US_TOPIC_0000001050128723__section1231643615527) should now work, but I cannot make it work.
Size & image provided by [`ArCameraIntrinsics.getImageDimensions();`](https://developer.huawei.com/consumer/en/doc/HMSCore-References-V5/camera_intrinsics-0000001051140882-V5#EN-US_TOPIC_0000001051140882__section646542420458) and `ArFrame.acquirePreviewImage().getWidth()` is always 1080x1440 (tested on Honor View 20 + Huawei P20 Pro)

[Code : Github hms-AREngine-demo fork](https://github.com/remmel/hms-AREngine-demo/blob/4530048dd09772310169d7e3669e40cae2492828/HwAREngineDemo/src/main/java/com/huawei/arengine/demos/java/recorder/RecorderActivity.java#L80)

Something else related, is the order width,height it not coherant with [`ArCameraIntrinsics.getImageDimensions();` //[1080,1440]](https://developer.huawei.com/consumer/en/doc/HMSCore-References-V5/camera_intrinsics-0000001051140882-V5#EN-US_TOPIC_0000001051140882__section646542420458)
as it returns [height,width] but ARConfigBase.setPreviewSize(width,height)

**Comment by Mike-mei** [comment]
@remmel 
1. The ARConfigBase.setPreviewSize(w,h) function isn't supported on the EMUI 9.x phone, this function will be available on EMUI 10.x phone in later versions
2. The first value returned means the long side, the second value returns means the short side.

**Comment by remmel** [comment]
Hi, 
1. but both of thoses phones have EMUI 10
- Honor 20 View : 10.1.0.231
- Huawei P20 Pro : 10.0.0.171

**Comment by Mike-mei** [comment]
The ARConfigBase.setPreviewSize(w,h) function will be supported on EMUI 10 phones in the 5.0.5 version, we will let you know when the new version released.

**Comment by remmel** [comment]
@Mike-mei , I confirm that this is now working :)
Checked with Honor 20 View (10.1.0.237) /Resolution checked (3264,2448) / com.huawei.hms:arenginesdk:2.15.0.1
Thanks !

**Comment by remmel** [comment]
I tried multiple resolutions on my Honor 20 View: [the documentation](https://developer.huawei.com/consumer/en/doc/HMSCore-References/config_base-0000001050119488-V5#EN-US_TOPIC_0000001050128723__section1231643615527) is missing some resolutions and others which are in the doc, but not working.
- ko: 8000,6000; 4000,3000; 1920,1080; 1600,1200; 1280,720; 1216,912; 1024,768; 768,576
- ok: 3264,2448; 2048,1536; 1440,1080 (default); 1280,960; 960,720; 640,480; 320,240

Can you update the doc with the new resolutions?

**Comment by Mike-mei** [comment]
Thank you for your suggestion, we will optimize the description in the [documentation](https://developer.huawei.com/consumer/en/doc/HMSCore-References/config_base-0000001050119488-V5#EN-US_TOPIC_0000001050128723__section1231643615527) in next week

**Comment by remmel** [comment]
Thanks! Thanks to your snippet, I found a larger resolution (tested) : 3968x2976
